### ISSUE TITLE
Questions about test results

### ISSUE THREAD

**Issue by Ruye-aa** [yewzijian/RegTR#13]
hello, I would like to commend you on your excellent work !
However, I am writing to you because I encountered some errors when running tests using the checkpoint  ' trained_models/3dmatch/ckpt/model-best.pth'  that was provided in [here](https://github.com/yewzijian/RegTR/releases/download/v1/trained_models.zip.) . 

![image](https://user-images.githubusercontent.com/76813112/229811587-7856c710-e1cd-4c45-a73b-6eb95a34ea1e.png)

I was wondering if you could kindly provide some assistance in resolving this matter?

Thank you in advance for your help.

Best regards

**Comment by solemotive** [comment]
> hello, I would like to commend you on your excellent work !您好，我想表扬您的出色工作！ However, I am writing to you because I encountered some errors when running tests using the checkpoint ' trained_models/3dmatch/ckpt/model-best.pth' that was provided in [here](https://github.com/yewzijian/RegTR/releases/download/v1/trained_models.zip.) .但是，我写信给您是因为我在使用[此处](https://github.com/yewzijian/RegTR/releases/download/v1/trained_models.zip.)提供的检查点 ' trained_models/3dmatch/ckpt/model-best.pth' 运行测试时遇到了一些错误。
> 
> ![image](https://user-images.githubusercontent.com/76813112/229811587-7856c710-e1cd-4c45-a73b-6eb95a34ea1e.png)
> 
> I was wondering if you could kindly provide some assistance in resolving this matter?我想知道您是否能为解决此事提供一些帮助？
> 
> Thank you in advance for your help.提前感谢您的帮助。
> 
> Best regards


I would like to ask if the following error occurred when I was running the train.py code. Do you have any methods to solve it：
```
06/26 18:54:31 [ERROR] trainer - <class 'RuntimeError'> at trainer.py:101 - CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
