### ISSUE TITLE
I want to know where to download 3dmatch dataset in .pth format?

### ISSUE THREAD

**Issue by superYuezhang** [yewzijian/RegTR#17]
The 3dmatch dataset download link for this repository and the predator download link give us the dataset in .ply format, and the folder branch doesn't match the path in .pkl file. Where should I download the dataset corresponding to the .pkl file?

**Comment by yewzijian** [comment]
I believe you mistakenly downloaded the raw dataset which is in .ply format. 

As described in the instructions, you need the processed 3DMatch dataset which provides the point clouds in .pth format. You can follow instructions from the Predator repo and download it using their download script. For convenience, the direct download link is [this](https://share.phys.ethz.ch/~gsg/Predator/data.zip).

**Comment by superYuezhang** [comment]
> 

Thanks! Predator original repository link not updated. The one you gave is the correct download link.
