### ISSUE TITLE
Question about benchmark source codes

### ISSUE THREAD

**Issue by Kitsunetic** [yewzijian/RegTR#28]
Hi yewzijian!
Thanks for sharing such a great work!

I'm reproducing the benchmark part and found some confusing parts, so I'm making this issue to clarify.

## Q1) Benchmark Source Code

<img width="576" alt="Screenshot 2024-12-25 at 16 41 40" src="https://github.com/user-attachments/assets/a399974f-f8f0-4dee-9809-6d0773d67eba" />

Is the table results are came from [here](https://github.com/yewzijian/RegTR/blob/0edee25cda6b1ac1c2b0ac686dcdf2593abf25ba/src/models/generic_reg_model.py#L179), right? I was confused because the benchmark file name is `benchmark_predator.py` not `benchmark_3dmatch.py`.

## Question 2)

If then, I got `results_str` and `mean_precision` variables from `benchmark_predator` function.

`results_str` is:
```
Scene	¦ prec.	¦ rec.	¦ re	¦ te	¦ samples	¦
Kitchen	¦ 0.980	¦ 0.980	¦ 1.765	¦ 0.041	¦ 449¦
Home 1	¦ 0.934	¦ 0.934	¦ 1.392	¦ 0.044	¦ 106¦
Home 2	¦ 0.717	¦ 0.717	¦ 1.689	¦ 0.052	¦ 159¦
Hotel 1	¦ 0.973	¦ 0.973	¦ 1.659	¦ 0.058	¦ 182¦
Hotel 2	¦ 0.949	¦ 0.949	¦ 1.317	¦ 0.046	¦  78¦
Hotel 3	¦ 1.000	¦ 1.000	¦ 2.119	¦ 0.043	¦  26¦
Study	¦ 0.889	¦ 0.889	¦ 1.632	¦ 0.058	¦ 234¦
MIT Lab	¦ 0.889	¦ 0.889	¦ 1.264	¦ 0.051	¦  45¦
Mean precision: 0.916: +- 0.084
Weighted precision: 0.921
Mean median RRE: 1.605: +- 0.261
Mean median RTE: 0.049: +- 0.006
```

and the `mean_precision` variable is `0.9162402564774712`.

I think
- `RR(%)` is this `mean_precision` variable.
- `RRE` and `RTE` is `Mean median RRE` and `Mean median RTE` of the table respectively.
Am I right?

**Comment by yewzijian** [comment]
Hi @Kitsunetic,

> Is the table results are came from [here](https://github.com/yewzijian/RegTR/blob/0edee25cda6b1ac1c2b0ac686dcdf2593abf25ba/src/models/generic_reg_model.py#L179), right? I was confused because the benchmark file name is benchmark_predator.py not benchmark_3dmatch.py.

Yes, that's the correct one. The benchmark codes follow the same evaluation scheme as Predator/3DMatch which considers the pointwise RMSE errors, hence I named it `benchmark_predator.py`. `benchmark_3dmatch.py` uses the evaluation scheme in "Deep Global Registration" which uses a different success criteria considering the translation/rotation errors.

> RR(%) is this mean_precision variable.
RRE and RTE is Mean median RRE and Mean median RTE of the table respectively.
Am I right?

Yes, that's right! The inference is non-deterministic so the results will differ slightly each time you run.

**Comment by Kitsunetic** [comment]
Thank you so much for detailed answer!!
Thank you!

**Comment by solemotive** [comment]
> Thank you so much for detailed answer!! Thank you!

I would like to ask if the following error occurred when I was running the train.py code. Do you have any methods to solve it：
```
06/26 18:54:31 [ERROR] trainer - <class 'RuntimeError'> at trainer.py:101 - CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
