### ISSUE TITLE
Setting parameter values for training of custom dataset

### ISSUE THREAD

**Issue by praffulp** [yewzijian/RegTR#6]
Hi @yewzijian! Thanks for sharing the codebase for your work. I am trying to train the network on custom data. As I went through the configuration, I found that for feature loss config., I need to set(r_p, r_n) which according to the paper are(m,2m), where m being the "voxel distance used in the final downsampling layer in the KPConv backbone". How do I figure out m for my dataset?

**Comment by yewzijian** [comment]
Hi, that depends on the KPConv parameter settings you use. For example, for the 3DMatch dataset, if you refer to its config [file](https://github.com/yewzijian/RegTR/blob/64e5b3f0ccc1e1a11b514eb22734959d32e0cec6/src/conf/3dmatch.yaml#L31), the input point clouds are initially downsampled to 2.5cm, but after 3 strided convolutions in the network, we set $r_p$ and $r_n$ to 20 (2.5 x 2 x 2 x 2) and 40 cm respectively. 

My personal experience is that the registration performance isn't too affected by the exact values of $r_p$ and $r_n$. However, it is sensitive to the KPConv convolutional backbone settings. I'll recommend having enough strided convolutions such that the final point clouds have somewhere between 200 to 700 points.


Zi Jian
